name: NinjaOne Playwright Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      npm_config_cache: ${{ github.workspace }}/.npm-store
      npm_version: 9.5.0
      node_version: 20.x
      URL: ${{ secrets.URL }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      INVALID_USERNAME: ${{ secrets.INVALID_USERNAME }}
      SECRET: ${{ secrets.SECRET }}
      CI: "true"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ${{ env.npm_config_cache }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Setup npm
        run: |
          corepack enable
          corepack prepare npm@${{ env.npm_version }} --activate
        env:
          npm_version: ${{ env.npm_version }}

      - name: Install test dependencies
        run: npm install --frozen-lockfile

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --fix-broken
          sudo apt-get install -y \
            libwebkit2gtk-4.0-37 \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            libasound2 \
            libgbm1

      - name: Install Playwright with dependencies
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: |
          mkdir -p junit-test-results
          report_file_path="junit-test-results/e2e-junit-results.xml"
          
          npx cucumber-js \
            --format json:test-results.json \
            --require-module ts-node/register
          
          if [ -f "test-results.json" ]; then
            npx cucumber-junit < test-results.json > "$report_file_path"
            chmod 755 "$report_file_path"
            echo "JUnit report file has been created."
          else
            echo "Cucumber JSON report file does not exist."
            exit 1
          fi
        env:
          URL: ${{ secrets.URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          INVALID_USERNAME: ${{ secrets.INVALID_USERNAME }}
          SECRET: ${{ secrets.SECRET }}
          CI: "true"
        continue-on-error: true

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: junit-test-results
          path: junit-test-results/e2e-junit-results.xml

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload Playwright JSON Results
        uses: actions/upload-artifact@v3
        with:
          name: playwright-json-results
          path: test-results

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: junit-test-results/e2e-junit-results.xml
